[version]
current = "0.1.2"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "bump: bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "README.md"
search = "    rev: v{current_version}"
