name: Release on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger the workflow on semver tags (e.g., v1.0.0).

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
